repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.0.0
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: check-merge-conflict
      - id: end-of-file-fixer

  - repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.9.3
    hooks:
      - id: isort

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args: ['--config=tox.ini', '--exit-zero']
        additional_dependencies: [
          flake8-docstrings,
          flake8-builtins,
          flake8-commas,
          flake8-comprehensions,
          flake8-logging-format,
          flake8-print,
          flake8-simplify,
          #flake8-spellcheck,
          flake8-rst-docstrings,
          flake8-bugbear,
          #flake8-eradicate,
          flake8-use_fstring,
          #pandas-vet, # need to disable once we enforce flake8, there are tons of false positives
        ]
        verbose: true
        #language_version: python3.8

  - repo: https://github.com/econchick/interrogate
    rev: 1.5.0  # or master if you're bold
    hooks:
      - id: interrogate
        files: 'bucky/'
        verbose: true

#
#  - repo: https://github.com/pre-commit/mirrors-pylint
#    rev: v2.6.0
#    hooks:
#      - id: pylint
#        language_version: python3.8
#
  - repo: https://github.com/terrencepreilly/darglint
    rev: v1.8.0
    hooks:
    - id: darglint
      args: ['--no-exit-code']
      verbose: true
