name: bucky
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.7
  - "libblas=*=*mkl"
  - numpy
  - pandas
  - geopandas
  - matplotlib
  - pyyaml
  - tqdm
  - scipy
  - networkx
  - openpyxl
  - descartes
  - pip
  - pip:
    - pyarrow
    - us
