name: bucky_gpu
channels:
  - conda-forge
  - defaults
dependencies:
  - "libblas=*=*mkl"
  - cupy/label/cupy_rc
  - cudatoolkit=11.5
  - cudnn
  - cutensor
  - nccl
  - numpy
  - pandas
  - geopandas
  - matplotlib
  - pyyaml
  - tqdm
  - scipy
  - networkx
  - openpyxl
  - descartes
  - pip
  - pip:
    - pyarrow
    - us
