name: bucky
channels:
  - conda-forge   #for up to date pyarrow
  - defaults
dependencies:
  - "libblas=*=*mkl"
  - numpy
  - pandas
  - geopandas
  - matplotlib
  - pyyaml
  - pyarrow
  - tqdm
  - scipy
  - networkx
  - openpyxl
  - descartes
  - pyarrow
  - us
