name: bucky_gpu
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.7
  - "libblas=*=*mkl"
  - cudatoolkit==11.4.2
  - cudnn
  - cutensor
  - nccl
  - numpy
  - pandas
  - geopandas
  - matplotlib
  - pyyaml
  - tqdm
  - scipy
  - networkx
  - openpyxl
  - descartes
  - pip
  - pip:
    - cupy>=10.0.0
    - pyarrow
    - us
