[tool.black]
line-length = 120
target-version = ['py38']
include = '\.pyi?$'
exclude = '''

(
  /(
     \.git          # root of the project
    | data 
  )/
)
'''

[tool.isort]
profile = "black"
line_length = 120

[tool.pylint.messages_control]
#disable = "C0330, C0326, C0103, E0602, W0511"

[tool.pylint.format]
max-line-length = "120"

[tool.interrogate]
verbose = 2
fail-under = 80
#generate-badge = "docs/source/_static"
